### ISSUE TITLE
Adjusting distribution can result in NaNs if q[i] == p[i]

### ISSUE THREAD

**Issue by sdtblck** [jaymody/speculative-sampling#5]
it's a somewhat rare edge case, but if `q[i] == p[i]` when resampling [here](https://github.com/jaymody/speculative-sampling/blob/03b4759da6e894bacdc2f396dc4fd88c913bf94d/main.py#L65), then you can get NaNs in the readjusted distribution. 

This can happen if temperature ~= 0, and the draft and target models are highly confident about the same token. This results in a distribution which is all zeros, and becomes NaNs when passed through `max_fn`.

```
>>> import numpy as np
>>> def max_fn(x):
...     x_max = np.where(x > 0, x, 0)
...     return x_max / np.sum(x_max)
... 
>>> max_fn(np.zeros((1, 100)))
<stdin>:3: RuntimeWarning: invalid value encountered in divide
array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan]])
```

the simple fix is to just check for equality of the two tensors, and if they're both equal, just sample from the target model distribution.

**Comment by sdtblck** [comment]
if you want batched sampling to work, you might need a different fix though

**Comment by jaymody** [comment]
The `nan`s occur here because we are dividing by zero in the denominator. This can only happen in the case where the input is all zeros, which only occurs when `q[i]` is **exactly** equal to `p[i]` (even a slight deviation of `p[i]` and `q[i]` would result in a positive denominator and thus no `nan`s).

But we don't need to worry about this case because if `p[i] == q[i]`, then we would never resample in the first place because the line [`np.random.random() < min(1, q[i][j] / p[i][j])`](https://github.com/jaymody/speculative-sampling/blob/03b4759da6e894bacdc2f396dc4fd88c913bf94d/main.py#L61) would always be `True` (i.e. we always accept) since `q[i][j] / p[i][j] = 1`.

Let me know if I'm missing something in the above analysis, otherwise I can close this issue.

**Comment by sdtblck** [comment]
yeah your analysis seems sound, but then I ran into this problem in my own private codebase... now scratching my head trying to figure out how!

I think this can be closed, it was probably a bug on my end

**Comment by jaymody** [comment]
I think in any case, if you wanted to make sure `max_fn` is nan safe, I think the correct solution would be to replace the `0` in the `max` with a very small epsilon:

```
>>> def max_fn(x, eps=1e-10):
...    x_max = np.where(x > 0, x, eps)
...    return x_max / np.sum(x_max)
>>> max_fn(np.zeros((1, 100)))
array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01]])
```
