### ISSUE TITLE
About the batch setting

### ISSUE THREAD

**Issue by Nero0113** [jaymody/speculative-sampling#8]
Can this approach be adapted to cases where the batch size is bigger than 1? I tried to change it, but failed.

**Comment by jaymody** [comment]
Speculative sampling can definitely be used with larger batch sizes.

This specific implementation, however, is built on-top of picoGPT which only supports a batch size of 1. PicoGPT can be extended to larger batch sizes either by modifying the code or using `jax.numpy` instead of `numpy` and applying `jax.vmap` to the GPT function.

This repo is mostly just for educational purposes, so your much better off just reimplementing this with PyTorch, say, on-top of some `huggingface` model.
