### ISSUE TITLE
Hi, a practical question about speculative decoding

### ISSUE THREAD

**Issue by leekum2018** [jaymody/speculative-sampling#9]
Thank you for your nice blog on speculative decoding in https://jaykmody.com/blog/speculative-sampling/. I can understand the mathematical principle on why speculative decoding is equivalent to naive decoding, but here I have a extreme case in which these two methods seem to have different results (both in greedy search setting).

The case can be illustrated simply as:
Draft model p has the probability prediction on the vocabulary: token_a: 20%, each of the rest has no more than 20% . Then the draft model will propose token_a.
Target model q has the probability prediction on the vocabulary: token_a: 30%, token_b: 50%.
According to the speculative decoding algorithm (or more specifically,  https://github.com/jaymody/speculative-sampling/blob/03b4759da6e894bacdc2f396dc4fd88c913bf94d/main.py#L61), the target model will accept token_a as q_a>p_a. But if using naive greedy search, token_b will be output by target model as token_b has the greatest probability.

There may be some misunderstanding in my thought. Your correction will be highly appreciated. Thanks!

**Comment by jaymody** [comment]
Good question!

There is a small misunderstanding here that easy to miss. Remember the distributions `p(x)` and `q(x)` represent the probability distributions **AFTER** temperature has been applied to the output of the models.

If we want to mimic greedy sampling, we must use a temperature of `temperature=0`. As a result, `p(x)` and `q(x)` would effectively become the following distributions:

`p(x) = token_a: 20%, rest less than 20%` becomes `p(x) = token_a: 100%, everything else 0`

`q(x) = token_a: 30%, token_b: 50%, ...` becomes `q(x) = token_a: 0%, token_b: 100%, everything else 0`

Thus, the line:

```
if np.random.random() < min(1, q[i][j] / p[i][j]):  # accepted
```

Would be rejected since `q[i][j] / p[i][j] = 0 / 1.0 = 0`.

Due to the rejection, we instead sample from `max_fn(q[i] - p[i]))` which would just be the distribution `token_b: 100%, everything else 0`, thus we only decode the token `token_b` which is obviously the same as greedy sampling.

Hope that helps.
